### ISSUE TITLE
Named character references are not allowed in ePub

### ISSUE THREAD

**Issue by jeltaqq** [kevinhendricks/KindleUnpack#46] opened 2023-10-08 10:46 UTC
Kindle seems to allow named character references```&nbsp;```, but ePub's xhtml is rejected, could you please replace it with a numeric character reference?

To fix this, we recommend that the XHTML file that contains &nbsp; use decimal (hexadecimal) notation instead.
```&#xA0; or &#160;```

In other cases it is recommended to use char notation.
```&times; is ×```.

**Comment by dougmassay** [comment] 2023-10-08 11:42
I'll let Kevin give his own opinion. But mine has always been that KindleUnpack is not really in the business of "fixing" anything. Not all kindlebooks are created from epubs--let alone epub3s (which is the only source where named entities are not allowed). KindleUnpack only creates an epub from the unpacked contents as a convenience (for later editing). It was never intended to provide a completely spec-compliant epub ready for public consumption. It's not really a conversion tool. KindleUnpack is intended to provide accurate markup from which the kindlebook was made. It tends to do so warts and all.

**Comment by kevinhendricks** [comment] 2023-10-08 15:35
And epub2 input to kindle preview allows named references and KindleUnpack will faithfully recreate that epub2.  Epub3 input to kindle should use no named references only numeric, and KindleUnpack will faithfully recreate that epub3.

But as dougmassay explained, not all input to Kindle Preview is a valid epub2 or a valid epub3.

So as far as I am concerned.  No bug exists when KindleUnpack is  given a Kindle book with valid epub2 or valid epub3.

So closing as not a bug.

**Closed** 2023-10-08 15:36 UTC

**Comment by kevinhendricks** [comment] 2023-10-08 17:09
FWIW, the python3 code to convert html named entities to numeric entities can be easily extracted from the ePub3-itizer code base here.  

See html_namedentities.py at https://github.com/kevinhendricks/ePub3-itizer/blob/master/src/html_namedentities.py

And the following snippet from that repo's plugin.py:

```
from html_namedentities import named_entities

IS_NAMED_ENTITY = re.compile("(&\w+;)")

# remap any html named enities to numeric entities
def convert_named_entities(text): 
    pieces = IS_NAMED_ENTITY.split(text)
    for i in range(1, len(pieces),2):
        piece = pieces[i]
        sval = named_entities.get(piece[1:],"")
        if sval != "":
            val = ord(sval)
            piece = "&#%d;" % val
            pieces[i] =piece
    return "".join(pieces)
```

So you could always add the code to handle that in a routine to post process every xhtml page if you need it.  But ingeneral post processing the output of KindleUnpack in Sigil or calibre makes the most sense as other epub2 remnants can still exist in KindleUnpacked code.

**Comment by jeltaqq** [comment] 2023-10-09 05:49
As you say, it's not a bug. I'll perform post-processing.
