### ISSUE TITLE
Unpacked files size doubled

### ISSUE THREAD

**Issue by kanhuangats** [kevinhendricks/KindleUnpack#26] opened 2019-04-03 18:10 UTC
So I have a azw3 comic book file, size 31MB.
After unpack, the size of output folder size is 91MB, almost all images.
How did this happen?

Is there a way to pack it back? Thanks

**Comment by dougmassay** [comment] 2019-04-03 18:18
Yes, it's called compression. The image files files are compressed in the kindlebook binary and KindleUnpack *unpacks* them. That's its purpose. There's no need to "pack it back" as you still have the unchanged original. But if you wanted to make changes and then rebuild the kindlebook, you should use KindlePreviewer or kindlegen to do that, Those are Amazon tools.

Perhaps you should say exactly what it is you're trying to accomplish with KindleUnpack.

**Comment by kevinhendricks** [comment] 2019-04-03 18:21
The ouput folder may contain both a mobi6 and an mobi8.  It should also have an epub.  It might also contain both high and low res versions of all images, and a source archive depening on if it is a joint mobi or not.

Please look inside the output folder for the epub alone and check its size both compressed and uncompressed.

**Comment by kanhuangats** [comment] 2019-04-03 18:25
> Yes, it's called compression. The image files files are compressed in the kindlebook binary and KindleUnpack _unpacks_ them. That's its purpose. There's no need to "pack it back" as you still have the unchanged original. But if you wanted to make changes and then rebuild the kindlebook, you should use KindlePreviewer or kindlegen to do that, Those are Amazon tools.
> 
> Perhaps you should say exactly what it is you're trying to accomplish with KindleUnpack.
> 
> Also make sure that you're unpacking to an empty directory.


First of all I don't think there is an algorithm capable of compressing 91MB jpg image files to 31MB.

I took a look, the output folder contains folders called Mobi7 and mobi8 and it seems that the images are duplicated inside these 2 folders?

**Comment by kevinhendricks** [comment] 2019-04-03 18:36
Yes, that is what I wrote.  You have multiple copies of the book in the output folder, one an older mobi, one a newer mobi (or just images for each as they share the images inside the .azw3.  And you have the epub ( for putting back into kindlegen, etc.  So 3 times 31 = 93.  You won't need all 3 versions.

**Comment by kanhuangats** [comment] 2019-04-03 18:40
> Yes, that is what I wrote. You have multiple copies of the book in the output folder, one an older mobi, one a newer mobi (or just images for each as they share the images inside the .azw3. And you have the epub ( for putting back into kindlegen, etc. So 3 times 31 = 93. You won't need all 3 versions.

OK. so the question is, is this how the original azw3 structured? containing 3 copies of same thing just for different ebook format?  When it is 'Unpacked', is the KindleUnpack creating all 3 versions from 1 single source?

**Comment by kevinhendricks** [comment] 2019-04-03 18:50
No.  A mobi is a database file wirh different record types. It is nothing like an epub.   What it contains depends on how the azw3/mobi was created in the first place.  With kindlegen you can easily create a joint mobi that has the pieces for older mobis (mobi 6 and 7) , a piece for newer mobis (mobi8), a shared set of image resources, and records to store the original source epub hat was used to generate it, as one database file with multiple record types.  There are versions that are only mobi 6/7 and versions that are only mobi 8, and some without the epub source archive.

KindleUnpacks job is to split out a mobi 6 if one exists, split out a mobi 8, and either unpack the epub source records, or alternativly convert the mobi8 records back into the epb that it was generated from (or as close as possible).

Once you have it in epub form, yo can edit the book and then send that epub back through kindlegen to create what you want.

Mobi formats are really ebooks encoded and compiled into a database package with indexes andthings.

**Comment by kevinhendricks** [comment] 2019-04-03 19:10
Closing this as this is not a bug or issue for KindleUnpack.  In the future a better place for general questions of this sort is the https://www.mobileread.com forum in either the Kindle or KindleUnpack support threads

**Closed by kevinhendricks** 2019-04-03 19:10 UTC
